### ISSUE TITLE
Create model for channel

### ISSUE THREAD

**Issue by ghost** [TheLycaeum/openradio#3]

**Comment by antojose** [comment]
Added the implementation for members list, as per http://stackoverflow.com/a/1113039.

@TODO: add the following public methods:
    #    - add_member(User) -> None
    #    - check_membership(User) -> bool
    #    - remove_member(User)

**Comment by antojose** [comment]
Added the implementations for the attributes c_owner and c_station.

@TODO: add the following attribute:
    #    - playlists -> list of Playlists

**Comment by ghost** [comment]
Done
