### ISSUE TITLE
Decide on URL scheme

### ISSUE THREAD

**Issue by ghost** [TheLycaeum/openradio#4]
Set URLs for the different operations

**Comment by afzalshahulhameed** [comment]
This is not practical on initial iteration as all the required views need not be decided and finalized upon.

**Comment by ghost** [comment]
Defined, but partially

**Comment by afzalSH** [comment]
Decided; https://github.com/TheLycaeum/openradio/wiki/RESTful-URL-mapping-for-the-project

**Comment by ghost** [comment]
Decided; https://github.com/TheLycaeum/openradio/wiki/RESTful-URL-mapping-for-the-project
